version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: monthly
  open-pull-requests-limit: 10
  reviewers:
  - mcclowes
  assignees:
  - mcclowes
  ignore:
  - dependency-name: html-pdf-chrome
    versions:
    - 0.6.1
  - dependency-name: lodash
    versions:
    - 4.17.20
    - 4.17.21
  - dependency-name: jest
    versions:
    - 26.6.3
  - dependency-name: mcclowes-scripts
    versions:
    - 0.11.1
  - dependency-name: http-proxy
    versions:
    - 1.18.1
  - dependency-name: elliptic
    versions:
    - 6.5.3
  - dependency-name: websocket-extensions
    versions:
    - 0.1.4
  - dependency-name: handlebars
    versions:
    - 4.7.6
  - dependency-name: mixin-deep
    versions:
    - 1.3.2
  - dependency-name: tar
    versions:
    - 4.4.10
  - dependency-name: url-parse
    versions:
    - 1.4.7
  - dependency-name: react-dev-utils
    versions:
    - 5.0.3
